ALTER TABLE users
  ADD COLUMN address_line1 VARCHAR(255),
  ADD COLUMN address_line2 VARCHAR(255),
  ADD COLUMN city VARCHAR(100),
  ADD COLUMN state VARCHAR(100),
  ADD COLUMN postal_code VARCHAR(20),
  ADD COLUMN latitude DECIMAL(9,6),
  ADD COLUMN longitude DECIMAL(9,6);
