-- Seed data for Off-Peak Deals application

-- Roles
INSERT INTO roles (name) VALUES 
  ('admin'),
  ('business'),
  ('consumer');

-- Users
-- Note: password hashes generated by PHP's password_hash function for 'password'
INSERT INTO users (username, password_hash, email) VALUES
  ('admin', '$2y$10$abcdefghijklmnopqrstuvCqR/db7z6sA.Q70NKO6YIzlsLYoaR.evy', 'admin@example.com'),
  ('business_user', '$2y$10$abcdefghijklmnopqrstuvCqR/db7z6sA.Q70NKO6YIzlsLYoaR.evy', 'business@example.com');

-- User roles mapping
INSERT INTO user_roles (user_id, role_id) VALUES
  (1, 1), -- admin user
  (2, 2); -- business user

-- Businesses
INSERT INTO businesses (name, description) VALUES
  ('Fox & Hounds', 'Traditional pub offering a variety of meals'),
  ('Kingston Tasty', 'Restaurant offering lunch specials and dinner deals');

-- Map businesses to owners (business_users)
INSERT INTO business_users (business_id, user_id) VALUES
  (1, 2),
  (2, 2);

-- Locations with latitude and longitude
INSERT INTO locations (business_id, name, address, city, state, postcode, phone, latitude, longitude) VALUES
  (1, 'Fox & Hounds Surbiton', '68 High Street', 'Surbiton', 'London', 'KT65AW', '020 1234 5678', 51.3890, -0.2989),
  (2, 'Kingston Tasty', '12 Market Place', 'Kingston upon Thames', 'London', 'KT11JX', '020 9876 5432', 51.4117, -0.3064);

-- Deals
INSERT INTO deals (location_id, title, description, price, day_of_week, start_time, end_time) VALUES
  (1, 'Becks Burger Night', 'Becks burger with fries and drink', 12.99, 'Thursday', '18:00:00', '22:00:00'),
  (2, 'Lunch Special', '2-course lunch special', 9.99, 'Monday', '12:00:00', '15:00:00');
